export const langs = {
    "auto": "auto",
    "en": "English",
    "de": "Deutsch",
    "fr": "Français",
    "es": "Español",
    "ja": "日本語",
    "pt-PT": "Português",
    "pt-BR": "Português (Brasil)",
    "it": "Italiano",
    "nl": "Nederlands",
    "pl": "Polski",
    "ru": "Русский",
    "zh": "简体中文",
    "sv": "Svenska",
    "cs": "Čeština",
    "tr": "Türkçe",
    "id": "Indonesia",
    "uk": "Українська",
};